vich_uploader:
    db_driver: orm

    mappings:
       media_object:
           uri_prefix: '%app.path.media_object%'
           upload_destination: '%pics_directory%'
           namer: Vich\UploaderBundle\Naming\OrignameNamer

